# Generated by Django 5.2.15 on 2026-07-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True)),
                ("licence", models.CharField(blank=True, max_length=80)),
                ("release_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["publisher", "name"],
            },
        ),
        migrations.CreateModel(
            name="IndicatorDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.indicatordomain",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("unit", models.CharField(max_length=40)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("COUNT", "Count"),
                            ("CURRENCY", "Currency"),
                            ("RATE", "Rate"),
                            ("RATIO", "Ratio"),
                            ("INDEX", "Index"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "is_additive",
                    models.BooleanField(
                        default=False,
                        help_text="True only for counts and currency totals that may be summed across places. Never True for rates, ratios, per-head or index values.",
                    ),
                ),
                (
                    "subject_scope",
                    models.CharField(
                        choices=[
                            ("PLACE", "Place"),
                            ("ORGANISATION", "Organisation"),
                            ("BOTH", "Both"),
                        ],
                        default="PLACE",
                        max_length=16,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="indicators",
                        to="core.indicatordomain",
                    ),
                ),
            ],
            options={
                "ordering": ["domain__code", "code"],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gss_code", models.CharField(db_index=True, max_length=9)),
                ("name", models.CharField(max_length=200)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("LAD", "Local authority district"),
                            ("WPC", "Westminster parliamentary constituency"),
                            ("COUNTRY", "Country"),
                            ("REGION", "Region / ITL1"),
                            ("ITL2", "ITL2"),
                            ("ITL3", "ITL3"),
                            ("MSOA", "MSOA"),
                            ("LSOA", "LSOA"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "nation",
                    models.CharField(
                        choices=[
                            ("E", "England"),
                            ("W", "Wales"),
                            ("S", "Scotland"),
                            ("N", "Northern Ireland"),
                            ("X", "Unknown / UK-wide"),
                        ],
                        editable=False,
                        help_text="Derived from the GSS code prefix on save.",
                        max_length=1,
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(help_text="Date this boundary set took effect."),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True, help_text="Null = current.", null=True
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only for tiers that nest cleanly. Null for constituencies.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.place",
                    ),
                ),
            ],
            options={
                "ordering": ["tier", "name"],
            },
        ),
        migrations.CreateModel(
            name="PlaceCrosswalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Apportionment fraction 0-1 of from_place attributable to to_place.",
                        max_digits=7,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("POPULATION", "Population"),
                            ("HOUSEHOLDS", "Households"),
                            ("AREA", "Area"),
                            ("WARD_COUNT", "Ward count (interim)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "from_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crosswalks_from",
                        to="core.place",
                    ),
                ),
                (
                    "to_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crosswalks_to",
                        to="core.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("CALENDAR_YEAR", "Calendar year"),
                            ("FINANCIAL_YEAR", "Financial year"),
                            ("QUARTER", "Quarter"),
                            ("MONTH", "Month"),
                            ("POINT", "Point in time"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Overrides indicator.unit when set.",
                        max_length=40,
                    ),
                ),
                (
                    "vintage",
                    models.CharField(
                        default="unversioned",
                        help_text="Release edition / restatement id. Non-null on purpose: NULLs are treated as distinct in Postgres unique constraints, which would let duplicate observations slip through.",
                        max_length=60,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PROVISIONAL", "Provisional"),
                            ("REVISED", "Revised"),
                            ("FINAL", "Final"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.indicator"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="core.place",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.source"
                    ),
                ),
            ],
            options={
                "ordering": ["place", "indicator", "period_start"],
            },
        ),
        migrations.CreateModel(
            name="ActivityClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("scheme", models.CharField(default="SIC-2007", max_length=40)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Cached depth: 0 section, 1 division, 2 group, ...",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.activityclass",
                    ),
                ),
            ],
            options={
                "ordering": ["scheme", "code"],
                "indexes": [
                    models.Index(
                        fields=["scheme"], name="core_activi_scheme_291fc1_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(fields=["tier"], name="core_place_tier_3694ed_idx"),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(fields=["nation"], name="core_place_nation_1bdc9e_idx"),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("gss_code", "valid_from"), name="uq_place_code_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="placecrosswalk",
            constraint=models.UniqueConstraint(
                fields=("from_place", "to_place", "basis"), name="uq_crosswalk"
            ),
        ),
        migrations.AddIndex(
            model_name="placeobservation",
            index=models.Index(
                fields=["place", "indicator", "period_start"],
                name="core_placeo_place_i_a50c00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="placeobservation",
            index=models.Index(
                fields=["indicator", "period_start"],
                name="core_placeo_indicat_11a2eb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="placeobservation",
            constraint=models.UniqueConstraint(
                fields=(
                    "indicator",
                    "place",
                    "period_start",
                    "period_end",
                    "source",
                    "vintage",
                ),
                name="uq_place_obs",
            ),
        ),
    ]
